README.md

README: improve content

---

src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala

Closes #8 
Note that there are tests that will fail until #7 and #9 are fixed.

test: add gitbase examples as tests

---

src/main/scala/tech/sourced/gitbase/spark/QueryBuilder.scala

Depends on #14 
This avoids throwing exceptions when the expressions cannot be compiled.

 do not throw exception when an expression cannot be compiled

---

src/main/scala/tech/sourced/gitbase/spark/udf/IsBinary.scala
src/main/scala/tech/sourced/gitbase/spark/udf/package.scala
src/test/scala/tech/sourced/gitbase/spark/udf/IsBinarySpec.scala

udf: implement is_binary udf

---

README.md

Fixes #12 
* Add LICENSE info to README.md

Add LICENSE info to README.md

---

.travis.yml
src/test/scala/tech/sourced/gitbase/spark/BaseGitbaseSpec.scala

ci: fix running bblfsh tests on travis

---

src/main/scala/tech/sourced/gitbase/spark/Query.scala
src/main/scala/tech/sourced/gitbase/spark/QueryBuilder.scala
src/main/scala/tech/sourced/gitbase/spark/rule/PushdownAggregations.scala
src/main/scala/tech/sourced/gitbase/spark/rule/PushdownJoins.scala
src/main/scala/tech/sourced/gitbase/spark/rule/PushdownTree.scala
src/main/scala/tech/sourced/gitbase/spark/rule/package.scala
src/test/scala/tech/sourced/gitbase/spark/QueryBuilderSpec.scala
src/test/scala/tech/sourced/gitbase/spark/rule/BaseRuleSpec.scala
src/test/scala/tech/sourced/gitbase/spark/rule/PushdownAggregationsSpec.scala

Coming from: #27
Closes #6
Closes #20

Pushdown aggregations

---

src/main/scala/tech/sourced/gitbase/spark/QueryBuilder.scala
src/test/scala/tech/sourced/gitbase/spark/QueryBuilderSpec.scala

Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>

Fix types used for casting

---

src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala

Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>

Add is_binary to test query.

---

Dockerfile

tag 5.7.0 does not exist, it's v5.7.0

fix dockerfile base image

---

src/main/scala/tech/sourced/gitbase/spark/Query.scala
src/main/scala/tech/sourced/gitbase/spark/QueryBuilder.scala
src/main/scala/tech/sourced/gitbase/spark/rule/PushdownTree.scala
src/test/scala/tech/sourced/gitbase/spark/QueryBuilderSpec.scala
src/test/scala/tech/sourced/gitbase/spark/rule/PushdownTreeSpec.scala

rule: push down limits to gitbase

---

README.md

See: https://github.com/src-d/gitbase/issues/639

docs: bump min version of gitbase to 0.18.x for uast functions compat

---

src/main/scala/tech/sourced/gitbase/spark/rule/PushdownTree.scala
src/main/scala/tech/sourced/gitbase/spark/udf/UastExtractParse.scala
src/test/scala/tech/sourced/gitbase/spark/rule/PushdownTreeSpec.scala

Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>

Push down only supported expressions on Projects

---

Makefile

Signed-off-by: kuba-- <kuba@sourced.tech>
Closes https://github.com/src-d/gitbase-spark-connector/issues/55

Docker push the latest only for releases.

---

src/main/scala/tech/sourced/gitbase/spark/udf/ParseCommitParents.scala
src/main/scala/tech/sourced/gitbase/spark/udf/package.scala
src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala
src/test/scala/tech/sourced/gitbase/spark/udf/ParseCommitParentsSpec.scala

udf: implement parse_commit_parents

---

docker-compose.yml

Signed-off-by: kuba-- <kuba@sourced.tech>

Use stable gitbase image v0.18.0

---

project/Dependencies.scala

Signed-off-by: kuba-- <kuba@sourced.tech>
Closes https://github.com/src-d/gitbase-spark-connector/issues/78

Upgrade enry to v1.7.1

---

src/main/scala/tech/sourced/gitbase/spark/rule/PushdownJoins.scala
src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala

Fixes #85
When the join data was not valid, the rule used `return`, but returned at the
top of the method, which caused all parent nodes of that join to be lost, so
the results were incorrect.
Moral of the story: don't use `return` in Scala like you would in any other language.

rule: fix PushdownJoins rule when there is a join with 3rd party datasources

---

README.md
docker-compose.yml
src/test/scala/tech/sourced/gitbase/spark/BaseGitbaseSpec.scala
src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala

Fixes #82
There's a fix that solves the issue where BLOB fields would be
treated as strings rather than binary.

update all gitbase versions to v0.20.0-beta3

---

README.md
build.sbt
docker-compose.yml
project/Dependencies.scala
src/main/scala/tech/sourced/gitbase/spark/Gitbase.scala
src/main/scala/tech/sourced/gitbase/spark/QueryBuilder.scala
src/main/scala/tech/sourced/gitbase/spark/package.scala
src/test/scala/tech/sourced/gitbase/spark/BaseGitbaseSpec.scala
src/test/scala/tech/sourced/gitbase/spark/DefaultSourceSpec.scala

Fixes https://github.com/src-d/gitbase/issues/807

replace mariadb driver with mysql driver
